services:
    client:
        container_name: frontend
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./client:/app
            - /app/node_modules
        restart: on-failure

    server:
        container_name: backend
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            PORT: $PORT
            DOCKER_MONGODB_URL: "mongodb://mongodb:27017/PostsDB"
        ports:
            - $PORT:$PORT
        volumes:
            - ./server:/app
            - /app/node_modules
        command: ["npx", "nodemon", "-L", "src/server.js"]
        restart: on-failure
        depends_on:
            - mongodb

    mongodb:
        container_name: mongoDB
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - /app:/data/db

    mongoexpress:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/PostsDB
        depends_on:
            - mongodb
        restart: on-failure
