services:
    ui:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./client:/app
            - /app/node_modules
        restart: always

    api:
        build:
            context: ./server
            dockerfile: Dockerfile

        environment:
            PORT: $PORT
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./server:/app
            - /app/node_modules
        restart: always
#   db:
#     image: mysql
#     restart: always
#     cap_add:
#       - SYS_NICE
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./api-server/db-setup.sql:/docker-entrypoint-initdb.d/setup.sql
#     ports:

#     environment:
#       <<: *common-variables
#       MYSQL_ROOT_PASSWORD: admin123
#       MYSQL_HOST: $MYSQL_HOST

#   api:
#     build:
#       context: ./api-server
#       target: dev
#     depends_on:
#       - db
#     volumes:
#       - ./api-server:/src
#       - /src/node_modules
#     command: npm run start:dev
#     ports:
#       - $API_PORT:$API_PORT
#     environment:
#       <<: *common-variables
#       PORT: $API_PORT
#       NODE_ENV: development

#   adminer:
#     image: adminer:latest
#     restart: unless-stopped
#     ports:
#       - 8080:8080
#     depends_on:
#       - db
#     environment:
#       ADMINER_DEFAULT_SERVER: db

#   ui:
#     stdin_open: true
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     build:
#       context: ./blog-ui
#     volumes:
#       - ./blog-ui:/src
#       - /src/node_modules
#     ports:
#       - $CLIENT_PORT:$CLIENT_PORT
